_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 2
                - 1
                - 3
                - 55
            "2":
                - 2
                - 1
                - 3
                - 55
            "3":
                - 2
                - 16
                - 23
                - 34
                - 35
                - 55
            "4": 3.9.18
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 64
gamma:
    value: 0.99
learning_rate:
    value: 0.0005
n_steps:
    value: 256
total_timesteps:
    value: 1000000
