apiVersion: apps/v1
kind: Deployment
metadata:
  name: prenet-detector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prenet-server
  template:
    metadata:
      labels:
        app: prenet-server
    spec:
      containers:
      - name: prenet-server
        image: asture123/prenet-detector
        env:

    
        ports:
        - containerPort: 5050
        volumeMounts:
        - mountPath: /dataset
          name: prenet-dataset

      volumes:
      - name: prenet-dataset
        persistentVolumeClaim:
          claimName: prenet-dataset-pvc
     
      nodeSelector:
        nodename: worker3
---
apiVersion: v1
kind: Service
metadata:
  name: prenet-server
  labels:
    run: prenet-server
spec:
  # type: LoadBalancer
  selector:
    app: prenet-server
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
    # nodePort: 32096
    # name: http
  # - port: 8920
  #   protocol: TCP
  #   targetPort: 8920
  #   # nodePort: 32120
  #   name: https

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prenet-dataset-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/pv/prenet-dataset"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prenet-dataset-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage



# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: emby-server-ingress
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: embymedia.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: emby-server
#             port:
#               number: 8096

---